// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKSyqLs--Wke5e-JCZzol5d2XIm5JVFQ',
    appId: '1:440325975726:web:47908590304e451466c73f',
    messagingSenderId: '440325975726',
    projectId: 'motiontodo8-aea2d',
    authDomain: 'motiontodo8-aea2d.firebaseapp.com',
    storageBucket: 'motiontodo8-aea2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1p56-9NThxH3qqPHbZJn7Lj0aKZKry6Y',
    appId: '1:440325975726:android:e095414e6abe3b3b66c73f',
    messagingSenderId: '440325975726',
    projectId: 'motiontodo8-aea2d',
    storageBucket: 'motiontodo8-aea2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5XsM0pZXaNjP8CSV3cG11HURP_YRrSAk',
    appId: '1:440325975726:ios:aa8e0937f7e1077b66c73f',
    messagingSenderId: '440325975726',
    projectId: 'motiontodo8-aea2d',
    storageBucket: 'motiontodo8-aea2d.firebasestorage.app',
    iosBundleId: 'com.example.flutterWeek8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5XsM0pZXaNjP8CSV3cG11HURP_YRrSAk',
    appId: '1:440325975726:ios:aa8e0937f7e1077b66c73f',
    messagingSenderId: '440325975726',
    projectId: 'motiontodo8-aea2d',
    storageBucket: 'motiontodo8-aea2d.firebasestorage.app',
    iosBundleId: 'com.example.flutterWeek8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcKSyqLs--Wke5e-JCZzol5d2XIm5JVFQ',
    appId: '1:440325975726:web:016fc9a26c3830fc66c73f',
    messagingSenderId: '440325975726',
    projectId: 'motiontodo8-aea2d',
    authDomain: 'motiontodo8-aea2d.firebaseapp.com',
    storageBucket: 'motiontodo8-aea2d.firebasestorage.app',
  );
}
